platform :ios, '9.0'
# 如果是业务组件，则必须要把user_frameworks!打开
use_frameworks!

#公司产品库
#source "https://git.hikvision.com.cn/scm/hik-system/cocoapods.git"

# 如果是业务组件，也就是动态库，下述这块必须添加，否则静态库和动态库一起用，则会编译失败
pre_install do |installer|
	def installer.verify_no_static_framework_transitive_dependencies; end

srcroot=`pwd`
`ruby Pods/C_HI_Framework/C_HI_Framework.framework/unionPrivancies.rb --srcroot="#{srcroot}" --project_name="${POD_NAME}_Example"`
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end


install! 'cocoapods', :deterministic_uuids => false
target '${POD_NAME}_Example' do

end
